# Generated by Django 3.1 on 2020-08-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200828_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='', max_length=50)),
                ('url', models.URLField(default='')),
                ('image', models.ImageField(upload_to='blog/static/images')),
            ],
        ),
    ]
