# Generated by Django 3.1 on 2020-08-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200825_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('cover_image', models.ImageField(upload_to=None)),
                ('text_snippet', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
